name: chocolatine

on:
 push:
  branches-ignore: 
    - 'ga-ignore-*'
 
 pull_request: 
  branches-ignore:
   - 'ga-ignore-*'
   
jobs:
  check_program_compilation:
   runs-on: ubuntu-latest
   ##container: epitechcontent/epitest-docker
   steps:
   - name: make_test
     uses: actions/checkout@v3
   - run: make 
   - name: make_clean_test
     uses: actions/checkout@v3
   - run: make clean
    
    
