name: chocolatine

on:
 push:
  branches-ignore: 
    - 'ga-ignore-*'
 
 pull_request: 
  branches-ignore:
   - 'ga-ignore-*'
   
env:
 Bin: 101pong
   
jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: check_coding_style
        uses: actions/checkout@v3
      - run : |
          check.sh $(pwd) $(pwd)
          cat coding-style-reports.log
          if [ -s $coding-style-reports.log ]
          i=1
          then
            while read -r line
            do                                                                                                                                                                       
              tab=( ${line//:/ } )
              yo=(${tab[0]})
              str=( ${yo//// } )
              echo "::error file=${str[1]},line=${tab[3]},title=${tab[2]} coding style error::${tab[3]}"
              ((i++))
            done < "coding-style-reports.log"
          fi

  check_program_compilation:
   runs-on: ubuntu-latest
   container: epitechcontent/epitest-docker
   timeout-minutes: 2
   steps:
   - name: make_test
     uses: actions/checkout@v3
   - run: make 
   - run: |
      if [[ -e $Bin ]] && [[ -x $Bin ]]
           then
             exit 0
           else
               exit 1
           fi
   - name: make_clean_test
     uses: actions/checkout@v3
   - run: make clean
    
    
