name: This is a chocolatine !!! Miam !!!
on:
    [push, pull_request]
env:
    MIRROR_URL: "git@github.com:Baguel/chocolatine.git"
    EXECUTABLES: "mysh"
jobs:
    check_coding_style:
        name: job1
        runs-on: ubuntu-latest
        container: ghcr.io/epitech/coding-style-checker:latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                check.sh $(pwd) $(pwd)
                if [ -s $coding-style-reports.log ]; then 
                cat coding-style-reports.log;
    check_program_compilation:
        name: job2
        runs-on: ubuntu-latest
        container: epitechcontent/epitest-docker
        steps:
            - uses: actions/checkout@v4
            - run: make
            - run: make clean
    run_tests:
        name: job3
        #needs: job2
        runs-on: ubuntu-latest
        container: epitechcontent/epitest-docker
        steps:
            - uses: actions/checkout@v4
            - run: make tests_run
    push_to_mirror:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' }}
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: pixta-dev/repository-mirroring-action@v1
              with:
                target_repo_url: ${{ env.MIRROR_URL }}
                ssh_private_key: ${{ secrets.GIT_KEY }}
